image: Visual Studio 2017

before_build:
  - ps: Update-AppveyorBuild -Version "$(Get-Content VERSION).build.$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - ps: src\build.ps1
  - ps: nuget\build.ps1
  - ps: templates\build.ps1
  - ps: doc\build.ps1

artifacts:
  - path: artifacts\Templates\*.vsix
  - path: artifacts\Documentation
    name: apidocs
  - path: artifacts\Packages\*.nupkg

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: NuGet
    on:
      appveyor_repo_tag: true
