var searchData=
[
  ['iaudio',['IAudio',['../interface_omega_engine_1_1_i_audio.html',1,'OmegaEngine']]],
  ['ichangenotify',['IChangeNotify',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_change_notify.html',1,'NanoByte::Common']]],
  ['icloneable',['ICloneable',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20dialog_20_3e',['ICloneable&lt; Dialog &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20localizablestring_20_3e',['ICloneable&lt; LocalizableString &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20localizablestringcollection_20_3e',['ICloneable&lt; LocalizableStringCollection &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionary_20_3e',['ICloneable&lt; XmlDictionary &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionaryentry_20_3e',['ICloneable&lt; XmlDictionaryEntry &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icommandexecutor',['ICommandExecutor',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor.html',1,'NanoByte::Common::Undo']]],
  ['icommandmanager',['ICommandManager',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager.html',1,'NanoByte::Common::Undo']]],
  ['icontextmenu',['IContextMenu',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu.html',1,'NanoByte::Common::Controls']]],
  ['icredentialprovider',['ICredentialProvider',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider.html',1,'NanoByte::Common::Net']]],
  ['ieditordialog',['IEditorDialog',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog.html',1,'NanoByte::Common::Controls']]],
  ['ihighlightcolor',['IHighlightColor',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_controls_1_1_i_highlight_color.html',1,'NanoByte::Common::Controls']]],
  ['iinputreceiver',['IInputReceiver',['../interface_omega_engine_1_1_input_1_1_i_input_receiver.html',1,'OmegaEngine::Input']]],
  ['imergeable',['IMergeable',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['inamed',['INamed',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inamed_3c_20asset_20_3e',['INamed&lt; Asset &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inamed_3c_20fileentry_20_3e',['INamed&lt; FileEntry &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inputbox',['InputBox',['https://common.nanobyte.de/class_nano_byte_1_1_common_1_1_controls_1_1_input_box.html',1,'NanoByte::Common::Controls']]],
  ['inputprovider',['InputProvider',['../class_omega_engine_1_1_input_1_1_input_provider.html',1,'OmegaEngine::Input']]],
  ['inspectionform',['InspectionForm',['https://common.nanobyte.de/class_nano_byte_1_1_common_1_1_controls_1_1_inspection_form.html',1,'NanoByte::Common::Controls']]],
  ['ipoolable',['IPoolable',['../interface_omega_engine_1_1_collections_1_1_i_poolable.html',1,'OmegaEngine::Collections']]],
  ['ipoolable_3c_20cpuparticle_20_3e',['IPoolable&lt; CpuParticle &gt;',['../interface_omega_engine_1_1_collections_1_1_i_poolable.html',1,'OmegaEngine::Collections']]],
  ['ipoolable_3c_20rendertarget_20_3e',['IPoolable&lt; RenderTarget &gt;',['../interface_omega_engine_1_1_collections_1_1_i_poolable.html',1,'OmegaEngine::Collections']]],
  ['ipositionable',['IPositionable',['../interface_omega_engine_1_1_i_positionable.html',1,'OmegaEngine']]],
  ['ipositionableoffset',['IPositionableOffset',['../interface_omega_engine_1_1_i_positionable_offset.html',1,'OmegaEngine']]],
  ['iprogress',['IProgress',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'NanoByte::Common::Tasks']]],
  ['iprogress_3c_20nanobyte_3a_3acommon_3a_3atasks_3a_3atasksnapshot_20_3e',['IProgress&lt; NanoByte::Common::Tasks::TaskSnapshot &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'']]],
  ['iprogress_3c_20tasksnapshot_20_3e',['IProgress&lt; TaskSnapshot &gt;',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_progress.html',1,'']]],
  ['ireferencecount',['IReferenceCount',['../interface_omega_engine_1_1_assets_1_1_i_reference_count.html',1,'OmegaEngine::Assets']]],
  ['iresetable',['IResetable',['../interface_omega_engine_1_1_i_resetable.html',1,'OmegaEngine']]],
  ['itask',['ITask',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task.html',1,'NanoByte::Common::Tasks']]],
  ['itaskhandler',['ITaskHandler',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler.html',1,'NanoByte::Common::Tasks']]],
  ['itextureprovider',['ITextureProvider',['../interface_omega_engine_1_1_graphics_1_1_i_texture_provider.html',1,'OmegaEngine::Graphics']]],
  ['itouchcontrol',['ITouchControl',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control.html',1,'NanoByte::Common::Controls']]],
  ['iundocommand',['IUndoCommand',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command.html',1,'NanoByte::Common::Undo']]],
  ['ivaluecommand',['IValueCommand',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command.html',1,'NanoByte::Common::Undo']]],
  ['iwizardpage',['IWizardPage',['https://common.nanobyte.de/interface_nano_byte_1_1_common_1_1_controls_1_1_i_wizard_page.html',1,'NanoByte::Common::Controls']]]
];
